# Generated by Django 4.2.27 on 2026-09-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
    ]
